### PR TITLE
Bug 1164195

### PR DESCRIPTION
**Pull request by TwiddleStick**
Attempted to fix issue 1 and 2: Changed the input parameters to accept resultType of type UNORDERED_NODE_ITERATOR_TYPE, introduced if-else statement declaring results to be of Ci.nsIDOMXPathResult.UNORDERED_NODE_ITERATOR_TYPE if resultType was defined, else ANY_TYPE.

### CODE REVIEW

**Comment by fabricedesre** [comment]
Can you upload your patch to https://bugzilla.mozilla.org/show_bug.cgi?id=1164195 ? This git repo is only a mirror but we don't use it to land code. Thanks!

**Comment by TwiddleStick** [comment]
Hey Fabrice, 

My bad I sent a pull request just before reading it was a read-only repository, sorry this is my first open-source patch attempt and I'm a total noob. Should I actually upload the patched code in a comment on Bugzilla or is there another way to go about this? Much thanks.

**Comment by fabricedesre** [comment]
No worries! You need to attach your patch as an attachment to https://bugzilla.mozilla.org/show_bug.cgi?id=1164195
You can find some information on patch submission at https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/How_to_Submit_a_Patch

**Comment by lonnen** [comment]
Can we close this PR?

Also, unsolicited protip: adding .patch to the end of a PR url will generate the patch for you. see: https://github.com/mozilla/gecko-dev/pull/60.patch

**Comment by fabricedesre** [comment]
We can close it, yes.

**Comment by Rikk** [comment]
yes

**Pull request closed without merging**
