### PR TITLE
Added my first patch and working on firefox for android

### PR DESCRIPTION
**Pull request by hellzone**
Please add me as an author for mozilla

### CODE REVIEW

**Comment by andreastt** [comment]
Please do not file PRs here, see https://developer.mozilla.org/docs/Mozilla/Developer_guide/How_to_Submit_a_Patch.

(Unfortunately I don’t have access to close this.)

**Comment by hellzone** [comment]
I wanted to get listed as one of the author

**Comment by kirillDanshin** [comment]
@hellzone submit a patch as you should. you should not use github PRs in this project.

**Comment by jyavenard** [comment]
https://developer.mozilla.org/docs/Mozilla/Developer_guide/How_to_Submit_a_Patch.

**Comment by hellzone** [comment]
Submitted a patch! Please have a look
https://reviewboard.mozilla.org/r/150084

**Comment by moz-hwine** [comment]
We do not use Pull Requests on this repo. Please see CONTRIBUTING or ReadMe file.

**Pull request closed without merging**
